run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - .git

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    min-confidence: 0
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
  goimports:
    local-prefixes: adminkaback
  staticcheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016"]
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Allow errors.New without wrapping in models package

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - gocyclo
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0
